name: Deploy infrastructure on LocalStack

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # “At 00:00 on Sunday.”
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  terraform:
    name: Deploy infrastructure using Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Set up Python 3.10
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Start LocalStack
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        run: |
          npm install -g @localstack/lstk
          lstk setup aws

          # Start LocalStack in the background
          lstk start

          # Wait for the LocalStack container to become ready
          echo "Waiting for LocalStack startup..."
          lstk status

          echo "Startup complete"

      - name: Deploy on Terraform
        run: |
          cd terraform
          lstk tf init
          lstk tf apply --auto-approve

      - name: Deploy Web Application
        run: |
          make run

      - name: Check deployed resources
        run: |
          sleep 10
          lstk aws apigatewayv2 get-apis
          lstk aws cognito-idp list-user-pools --max-results 1

      - name: Send a Slack notification
        if: failure() || github.event_name != 'pull_request'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}> | <{run_url}|View Workflow run>"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Generate a Diagnostic Report
        if: failure()
        run: |
          curl -s localhost:4566/_localstack/diagnose | gzip -cf > diagnose.json.gz

      - name: Upload the Diagnostic Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: diagnose.json.gz
          path: ./diagnose.json.gz

  cloudformation:
    name: Deploy infrastructure using CloudFormation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Start LocalStack
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
          LOCALSTACK_DNS_ADDRESS: 0
        run: |
          npm install -g @localstack/lstk
          lstk setup aws
          docker pull localstack/localstack-pro:latest

          # Start LocalStack in the background
          lstk start

          # Wait for the LocalStack container to become ready
          echo "Waiting for LocalStack startup..."
          lstk status

          echo "Startup complete"

      - name: Deploy on CloudFormation
        run: |
          cd cloudformation
          STACK="stack1"
          CF_FILE="ecsapi-demo-cloudformation.yaml"
          lstk aws cloudformation create-stack --stack-name $STACK --template-body file://$CF_FILE

      - name: Deploy Web Application
        run: |
          make run

      - name: Check deployed resources
        run: |
          sleep 10
          lstk aws apigatewayv2 get-apis
          lstk aws cognito-idp list-user-pools --max-results 1

      - name: Send a Slack notification
        if: failure() || github.event_name != 'pull_request'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}> | <{run_url}|View Workflow run>"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Generate a Diagnostic Report
        if: failure()
        run: |
          curl -s localhost:4566/_localstack/diagnose | gzip -cf > diagnose.json.gz

      - name: Upload the Diagnostic Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: diagnose.json.gz
          path: ./diagnose.json.gz
